### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by shabansamani** [Checoru/prj-rev-bwfs-dasmoto#5]
Rather than having each section in one big \<div>, have them in separate \<div>'s instead. This will make your page more modular and will give your more flexibility in styling and positioning elements.

https://github.com/Checoru/prj-rev-bwfs-dasmoto/blob/ef7a7d7921a790419c7bda955e71664962bdd137/Dasmoto%20Art/dasmoto.html#L10-L33

**Comment by Checoru** [comment]
Thanks.
